// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcHI59uwhBHE9tgQlLwt1Lbc8Q5lORAyU',
    appId: '1:75382635935:web:d6bb7eca13382163ab11aa',
    messagingSenderId: '75382635935',
    projectId: 'twitter-6ba71',
    authDomain: 'twitter-6ba71.firebaseapp.com',
    storageBucket: 'twitter-6ba71.appspot.com',
    measurementId: 'G-5ZYN7GW6BJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY8LQ0ZZeCXKpEipEfE8I4pqRnL_HiDRc',
    appId: '1:75382635935:android:3b4e2a3b4a3c8d7fab11aa',
    messagingSenderId: '75382635935',
    projectId: 'twitter-6ba71',
    storageBucket: 'twitter-6ba71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy5xa70X30qD39rQpZN3U6CNBhvXiZ7hE',
    appId: '1:75382635935:ios:a2dc757e08c63060ab11aa',
    messagingSenderId: '75382635935',
    projectId: 'twitter-6ba71',
    storageBucket: 'twitter-6ba71.appspot.com',
    iosBundleId: 'com.example.demo2Form',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy5xa70X30qD39rQpZN3U6CNBhvXiZ7hE',
    appId: '1:75382635935:ios:c7563d205da0c511ab11aa',
    messagingSenderId: '75382635935',
    projectId: 'twitter-6ba71',
    storageBucket: 'twitter-6ba71.appspot.com',
    iosBundleId: 'com.example.demo2Form.RunnerTests',
  );
}
